=== kamilZ01/Technologie_XML_zad2/public_html/filmy.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:ga="http://example.org/genres"
           xmlns:kr="http://example.org/countries">
    <xs:import schemaLocation="gatunki.xsd"
               namespace="http://example.org/genres"/>
    <xs:import schemaLocation="kraje.xsd"
               namespace="http://example.org/countries"/>
    
    <xs:element type="filmyType" name="filmy">
      
        <xs:key name="key_gatunekID">
            <xs:selector xpath="./gatunki/*"/>
            <xs:field xpath="@gatunek_id"/>
        </xs:key>
        <xs:keyref name="keyref_gatunek" refer="key_gatunekID">
            <xs:selector xpath="./film"/>
            <xs:field xpath="@gatunek"/>
        </xs:keyref>
        
        <xs:key name="key_krajID">
            <xs:selector xpath="./kraje/*"/>
            <xs:field xpath="@kraj_id"/>
        </xs:key>
        <xs:keyref name="keyref_kraj" refer="key_krajID">
            <xs:selector xpath="./film"/>
            <xs:field xpath="@kraj"/>
        </xs:keyref>
    </xs:element>
    
    <xs:complexType name="filmyType">
        <xs:sequence>
            <xs:element name="dane_techniczne" type="dane_techniczneType"/>
            <xs:element name="gatunki" type="ga:gatunkiType" />
            <xs:element name="kraje" type="kr:krajeType" />
            <xs:element name="film" type="filmType" minOccurs="1" maxOccurs="22"/>
            <xs:element name="prawa_autorskie" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <!-- dane_techniczne -->
    <xs:complexType name="dane_techniczneType">
        <xs:sequence>
            <xs:group ref="dane_techniczneGroup"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:group name="dane_techniczneGroup">
        <xs:sequence>
            <xs:element name="tytuł" type="xs:string" />
            <xs:element name="informacje" type="xs:string" />
            <xs:element name="autorzy" type="autorzyType" />
        </xs:sequence>
    </xs:group>
    
    <xs:complexType name="autorzyType" >
        <xs:sequence>
            <xs:element name="twórca" maxOccurs="2" type="twórcaType" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="twórcaType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                        <xs:attribute name="nrIndeksu" use="required" type="indexRest"/>
            </xs:extension>      
        </xs:simpleContent>
    </xs:complexType>
    
    <xs:simpleType name="indexRest">
            <xs:restriction base="xs:nonNegativeInteger">
                <xs:pattern value="[0-9]{6}" />  
            </xs:restriction>
    </xs:simpleType>
    
    <!-- film -->
   
    <xs:complexType name="filmType">
        <xs:sequence>
            <xs:element name="bazy_filmowe" type="bazyType" />
            <xs:element name="dane" type="daneType" />
            <xs:element name="oceny" type="ocenyType" />
            <xs:element name="premiery" type="premieryType" />
            <xs:element name="wypożyczenie" type="wypożyczenieType" />
            <xs:element name="kolejność" type="kolejnośćType" />
        </xs:sequence>
        <xs:attributeGroup ref="filmattrGroup" />
    </xs:complexType>
    
   <xs:attributeGroup name="filmattrGroup">
       <xs:attribute name="id" type="xs:ID" use="required"/>
       <xs:attribute name="gatunek" type="xs:string" use="required" />
       <xs:attribute name="kraj" type="xs:string" use="required" />
   </xs:attributeGroup>
    
   <xs:complexType name="bazyType"> 
       <xs:attribute name="filmweb" use="required" type="xs:string"/>
       <xs:attribute name="imdb" use="required" type="xs:string"/>
   </xs:complexType>
   
   <xs:complexType name="daneType">
       <xs:sequence>
           <xs:element name="tytuł_org" type="lengthRest"/>
           <xs:element name="tytuł_pl"  type="xs:string"/>
           <xs:element name="opis" type="lengthRest"/>
           <xs:element name="reżyseria" type="lengthRest"/>
           <xs:element name="scenariusz" type="lengthRest"/>
           <xs:element name="boxoffice" type="boxRest"/>
       </xs:sequence>
   </xs:complexType>
   
   <xs:simpleType name="lengthRest">
       <xs:restriction base="xs:string">
           <xs:minLength value="1"/>
       </xs:restriction>
   </xs:simpleType>
   
   <xs:complexType name="boxRest">
       <xs:simpleContent>
           <xs:extension base="xs:string">
               <xs:attribute name="waluta" type="walutaRest"/>
           </xs:extension>
       </xs:simpleContent>
    </xs:complexType>
    <xs:simpleType name="walutaRest">
        <xs:restriction base="xs:string">
            <xs:enumeration value="USD"/>
            <xs:enumeration value="PLN"/>
            <xs:enumeration value="EUR"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="ocenyType">
        <xs:sequence>
            <xs:element name="filmweb"  type="ocenaTyp"/>
            <xs:element name="imdb"  type="ocenaTyp"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="ocenaTyp">
        <xs:restriction base="xs:decimal">
            <xs:fractionDigits value="1"/>
            <xs:totalDigits value="2"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="premieryType">
        <xs:sequence>
            <xs:element name="polska"  type="polskaRest"/>
            <xs:element name="świat"  type="xs:date"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="polskaRest">
        <xs:union>
            <xs:simpleType>
                <xs:restriction base="xs:date"/>
            </xs:simpleType>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:length value="0" />
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>
    
    
     <xs:complexType name="wypożyczenieType">
        <xs:sequence>
            <xs:element name="data_wypożyczenia"  type="xs:date"/>
            <xs:element name="data_zwrotu"  type="xs:date"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="kolejnośćType">
        <xs:sequence>
            <xs:element name="numer"  type="numerRest"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="numerRest">
       <xs:simpleContent>
           <xs:extension base="numersRest">
               <xs:attribute name="idNumer" >
                    <xs:simpleType>
                        <xs:restriction base="xs:positiveInteger">
                            <xs:minInclusive value="1"/>
                            <xs:maxInclusive value="22"/>
                        </xs:restriction>
                    </xs:simpleType>
               </xs:attribute>
           </xs:extension>
       </xs:simpleContent>
    </xs:complexType>
    
    <xs:simpleType name="numersRest">
        <xs:restriction base="xs:string">
                <xs:pattern value="/22"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== kamilZ01/Technologie_XML_zad2/public_html/filmy.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="style/style.css"?>

<filmy xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:ga="http://example.org/genres"
       xmlns:kr="http://example.org/countries"
       xs:noNamespaceSchemaLocation="filmy.xsd">

    <dane_techniczne>
        <tytuł>
           Filmoteka
        </tytuł>
        <informacje>Lista filmów w wypożyczalni. Filmy zostały ponumerowane oraz przyporządkowane poprez atrybuty odpowiednim gatunkom i krajom produkcji.</informacje>
        <autorzy>
            <twórca nrIndeksu="224478">Dominik Cegiełka</twórca>
            <twórca nrIndeksu="224546">Kamil Zarych</twórca>
        </autorzy>
    </dane_techniczne>

    <!-- Gatunki filmowe -->
    <gatunki>
        <ga:gatunek gatunek_id="akcja">Akcja</ga:gatunek>
        <ga:gatunek gatunek_id="dokumentalny">Dokumentalny</ga:gatunek>
        <ga:gatunek gatunek_id="dramat">Dramat</ga:gatunek>
        <ga:gatunek gatunek_id="fantasy">Fantasy</ga:gatunek>
        <ga:gatunek gatunek_id="horror">Horror</ga:gatunek>
        <ga:gatunek gatunek_id="komedia">Komedia</ga:gatunek>
        <ga:gatunek gatunek_id="kryminał">Kryminał</ga:gatunek>
        <ga:gatunek gatunek_id="przygodowy">Przygodowy</ga:gatunek>
        <ga:gatunek gatunek_id="thriller">Thriller</ga:gatunek>
        <ga:gatunek gatunek_id="sci-fi">Sci-Fi</ga:gatunek>
        <ga:gatunek gatunek_id="biograficzny">Biograficzny</ga:gatunek>
    </gatunki>

    <!--Kraje produkcji -->
    <kraje>
        <kr:kraj kraj_id="AUS">Australia</kr:kraj>
        <kr:kraj kraj_id="FR">Francja</kr:kraj>
        <kr:kraj kraj_id="PL">Polska</kr:kraj>
        <kr:kraj kraj_id="US">Stany Zjednoczone</kr:kraj>
        <kr:kraj kraj_id="UK">Wielka Brytania</kr:kraj>
        <kr:kraj kraj_id="CA">Kanada</kr:kraj>
        <kr:kraj kraj_id="HK">Hongkong</kr:kraj>
        <kr:kraj kraj_id="BR">Brazylia</kr:kraj>
        <kr:kraj kraj_id="DK">Dania</kr:kraj>
        <kr:kraj kraj_id="SE">Szwecja</kr:kraj>
        <kr:kraj kraj_id="RU">Rosja</kr:kraj>
        <kr:kraj kraj_id="IN">Indie</kr:kraj>
        <kr:kraj kraj_id="RPA">Republika Południowej Afryki</kr:kraj>
        <kr:kraj kraj_id="ES">Hiszpania</kr:kraj>
        <kr:kraj kraj_id="IT">Włochy</kr:kraj>
    </kraje>

    <!-- Lista filmów -->
    <film id="Joker" gatunek="dramat" kraj="CA">
        <bazy_filmowe filmweb="https://www.filmweb.pl/film/Joker-2019-810167" imdb="https://www.imdb.com/title/tt7286456/" />
        <dane>
            <tytuł_org>Joker (2019)</tytuł_org>
            <tytuł_pl></tytuł_pl>
            <opis>Historia jednego z cieszących się najgorszą sławą superprzestępców uniwersum DC — Jokera. Przedstawiony przez Phillipsa obraz śledzi losy kultowego czarnego charakteru, człowieka zepchniętego na margines. To nie tylko kontrowersyjne studium postaci, ale także opowieść ku przestrodze w szerszym kontekście.</opis>
            <reżyseria>Todd Phillips</reżyseria>
            <scenariusz>Todd Phillips, Scott Silver</scenariusz>
            <boxoffice waluta="USD">548 290 190</boxoffice>
        </dane>
         <oceny>
            <filmweb>8.7</filmweb>
            <imdb>8.9</imdb>
        </oceny>
        <premiery>
            <polska>2019-10-04</polska>
            <świat>2019-08-31</świat>
        </premiery>
        <wypożyczenie>
            <data_wypożyczenia>2019-10-08</data_wypożyczenia>
            <data_zwrotu>2019-10-16</data_zwrotu>
        </wypożyczenie>
         <kolejność>
            <numer idNumer="1">/22</numer>
        </kolejność>
    </film>
    <film id="Smith" gatunek="akcja" kraj="US">
        <bazy_filmowe filmweb="https://www.filmweb.pl/Mr.Mrs.Smith" imdb="https://www.imdb.com/title/tt0356910/?ref_=fn_al_tt_1" />
        <dane>
            <tytuł_org>Mr. &amp; Mrs. Smith</tytuł_org>
            <tytuł_pl>Pan i Pani Smith</tytuł_pl>
            <opis>Para płatnych zabójców pracujących dla dwóch tajnych agencji wiedzie monotonne małżeńskie życie. Niespodziewanie dostają zlecenie na siebie nawzajem.</opis>
            <reżyseria>Doug Liman</reżyseria>
            <scenariusz>Simon Kinberg</scenariusz>
            <boxoffice waluta="USD">478 207 520</boxoffice>
        </dane>
         <oceny>
            <filmweb>6.7</filmweb>
            <imdb>6.5</imdb>
        </oceny>
        <premiery>
            <polska>2005-08-05</polska>
            <świat>2005-06-07</świat>
        </premiery>
        <wypożyczenie>
            <data_wypożyczenia>2018-09-08</data_wypożyczenia>
            <data_zwrotu>2018-11-25</data_zwrotu>
        </wypożyczenie>
         <kolejność>
            <numer idNumer="2">/22</numer>
        </kolejność>
    </film>
    <film id="mRycerz" gatunek="sci-fi" kraj="UK">
        <bazy_filmowe filmweb="https://www.filmweb.pl/Mroczny.Rycerz" imdb="https://www.imdb.com/title/tt0468569/" />
        <dane>
            <tytuł_org>The Dark Knight</tytuł_org>
            <tytuł_pl>Mroczny Rycerz</tytuł_pl>
            <opis>Batman, z pomocą porucznika Gordona oraz prokuratora Harveya Denta, występuje przeciwko przerażającemu i nieobliczalnemu Jokerowi, który chce pogrążyć Gotham City w chaosie.</opis>
            <reżyseria>Christopher Nolan</reżyseria>
            <scenariusz>Christopher Nolan, Jonathan Nolan</scenariusz>
            <boxoffice waluta="USD">1 004 558 444</boxoffice>
        </dane>
         <oceny>
            <filmweb>8.0</filmweb>
            <imdb>9.0</imdb>
        </oceny>
        <premiery>
            <polska>2008-08-08</polska>
            <świat>2008-07-14</świat>
        </premiery>
        <wypożyczenie>
            <data_wypożyczenia>2009-02-14</data_wypożyczenia>
            <data_zwrotu>2009-03-01</data_zwrotu>
        </wypożyczenie>
         <kolejność>
            <numer idNumer="3">/22</numer>
        </kolejność>
    </film>
    <film id="Avengers" gatunek="akcja" kraj="US">
        <bazy_filmowe filmweb="https://www.filmweb.pl/film/Avengers%3A+Koniec+gry-2019-790542" imdb="https://www.imdb.com/title/tt4154796/" />
        <dane>
            <tytuł_org>Avengers: Endgame</tytuł_org>
            <tytuł_pl>Avengers: Koniec gry</tytuł_pl>
            <opis>Po wymazaniu połowy życia we Wszechświecie przez Thanosa, Avengersi starają się zrobić wszystko co konieczne, aby pokonać szalonego tytana.</opis>
            <reżyseria>Anthony Russo, Joe Russo</reżyseria>
            <scenariusz>Christopher Markus, Stephen McFeely</scenariusz>
            <boxoffice waluta="USD">2 797 800 564</boxoffice>
        </dane>
         <oceny>
            <filmweb>8.2</filmweb>
            <imdb>8.5</imdb>
        </oceny>
        <premiery>
            <polska>2019-04-25</polska>
            <świat>2019-04-22</świat>
        </premiery>
        <wypożyczenie>
            <data_wypożyczenia>2019-05-06</data_wypożyczenia>
            <data_zwrotu>2019-06-15</data_zwrotu>
        </wypożyczenie>
         <kolejność>
            <numer idNumer="4">/22</numer>
        </kolejność>
    </film>
    <film id="bHero" gatunek="sci-fi"   kraj="US">
        <bazy_filmowe filmweb="https://www.filmweb.pl/Mroczny.Rycerz" imdb="https://www.imdb.com/title/tt2245084/" />
        <dane>
            <tytuł_org>Big Hero 6</tytuł_org>
            <tytuł_pl>Wielka Szóstka</tytuł_pl>
            <opis>Młody geniusz Hiro Hamada wraz ze swoim robotem Baymaxem zostaje uwikłany w plan zniszczenia miasta San Fransokyo.</opis>
            <reżyseria>Don Hall, Chris Williams</reżyseria>
            <scenariusz>Jordan Roberts, Robert L. Baird,</scenariusz>
            <boxoffice waluta="USD">652 127 828</boxoffice>
        </dane>
         <oceny>
            <filmweb>7.7</filmweb>
            <imdb>7.8</imdb>
        </oceny>
        <premiery>
            <polska>2014-11-28</polska>
            <świat>2014-10-23</świat>
        </premiery>
        <wypożyczenie>
            <data_wypożyczenia>2015-12-12</data_wypożyczenia>
            <data_zwrotu>2015-12-27</data_zwrotu>
        </wypożyczenie>
         <kolejność>
            <numer idNumer="5">/22</numer>
        </kolejność>
    </film>
    <film id="Wonder" gatunek="dramat"  kraj="HK">
        <bazy_filmowe filmweb="https://www.filmweb.pl/film/Cudowny+ch%C5%82opak-2017-776387" imdb="https://www.imdb.com/title/tt2543472/" />
        <dane>
            <tytuł_org>Wonder</tytuł_org>
            <tytuł_pl>Cudowny chłopak</tytuł_pl>
            <opis>Auggie od urodzenia ma zdeformowaną twarz. W nowej szkole chłopiec chce udowodnić rówieśnikom, że piękno to więcej niż wygląd.</opis>
            <reżyseria>Stephen Chbosky</reżyseria>
            <scenariusz>Steve Conrad, Jack Thorne</scenariusz>
            <boxoffice waluta="USD">305 900 041</boxoffice>
        </dane>
         <oceny>
            <filmweb>7.9</filmweb>
            <imdb>8.0</imdb>
        </oceny>
        <premiery>
            <polska>2018-01-19</polska>
            <świat>2017-11-15</świat>
        </premiery>
        <wypożyczenie>
            <data_wypożyczenia>2019-04-22</data_wypożyczenia>
            <data_zwrotu>2019-08-19</data_zwrotu>
        </wypożyczenie>
         <kolejność>
            <numer idNumer="6">/22</numer>
        </kolejność>
    </film>
    <film id="Exorcist" gatunek="horror"  kraj="US">
        <bazy_filmowe filmweb="https://www.filmweb.pl/film/Cudowny+ch%C5%82opak-2017-776387" imdb="https://www.imdb.com/title/tt2543472/" />
        <dane>
            <tytuł_org>The Exorcist</tytuł_org>
            <tytuł_pl>Egzorcysta</tytuł_pl>
            <opis>Kiedy dwunastoletnia dziewczynka zostaje opętana przez diabła, a lekarze nie są w stanie jej pomóc, przerażona matka kontaktuje się z egzorcystą.</opis>
            <reżyseria>William Friedkin</reżyseria>
            <scenariusz>William Peter, Blatty</scenariusz>
            <boxoffice waluta="USD">441 306 145</boxoffice>
        </dane>
        <oceny>
            <filmweb>7.5</filmweb>
            <imdb>8.0</imdb>
        </oceny>
